/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface MarkdownHtmlDetection {
  htmlTagCount: number
  tags: Record<string, number>
  hasLikelyHtmlBlocks: boolean
}

export interface MarkdownImportPlanOptions {
  maxDocChars: number
  targetDocChars?: number
  split: MarkdownSplitStrategy
  rawHtmlMode?: MarkdownRawHtmlMode
}

export interface MarkdownImportPlanPart {
  markdown: string
  suggestedTitle?: string
  estimatedChars: number
}

export interface MarkdownImportPlanResult {
  normalizedMarkdown: string
  parts: Array<MarkdownImportPlanPart>
  html: MarkdownHtmlDetection
}

export interface MarkdownParseOptions {
  rawHtmlMode?: MarkdownRawHtmlMode
}

export declare const enum MarkdownRawHtmlMode {
  Drop = 'Drop',
  CodeBlock = 'CodeBlock'
}

export interface MarkdownSplitStrategy {
  type: string
  level?: number
}

export declare function parseMarkdown(input: string, options: MarkdownParseOptions): string

export declare function planMarkdownImport(markdown: string, options: MarkdownImportPlanOptions): MarkdownImportPlanResult
