/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeStorageEngine {
  static open(dbPath: string): Promise<NativeStorageEngine>
  static openSync(dbPath: string): NativeStorageEngine
  close(): Promise<void>
  beginTransaction(): Promise<NativeTransactionHandle>
  aiModelSelectionGet(txId: string | undefined | null, usage: string, scopeType: string, scopeId: string): Promise<AiModelSelectionDto | null>
  aiModelSelectionGetMany(txId: string | undefined | null, usage: string, scopeType: string, scopeIds: Array<string>): Promise<Array<AiModelSelectionDto>>
  aiModelSelectionUpsert(txId: string | undefined | null, input: UpsertAiModelSelectionDto): Promise<AiModelSelectionDto>
  aiModelSelectionDelete(txId: string | undefined | null, usage: string, scopeType: string, scopeId: string): Promise<void>
  aiSettingsListProviderConfigs(txId: string | undefined | null, usage: string): Promise<Array<AiProviderConfigDto>>
  aiSettingsUpsertProviderConfig(txId: string | undefined | null, input: UpsertAiProviderConfigDto): Promise<void>
  aiSettingsDeleteProviderConfigsNotIn(txId: string | undefined | null, usage: string, ids: Array<string>): Promise<void>
  aiSettingsListApiKeys(txId?: string | undefined | null): Promise<Array<AiApiKeyDto>>
  aiSettingsFindApiKeyById(txId: string | undefined | null, id: string): Promise<AiApiKeyDto | null>
  aiSettingsClearDefaultApiKeys(txId: string | undefined | null, baseUrl: string, updatedAt: number): Promise<void>
  aiSettingsInsertApiKey(txId: string | undefined | null, apiKey: AiApiKeyDto): Promise<void>
  aiSettingsUpdateApiKey(txId: string | undefined | null, id: string, data: UpdateAiApiKeyDataDto): Promise<void>
  aiSettingsSetApiKeyDefault(txId: string | undefined | null, id: string, isDefault: boolean, updatedAt: number): Promise<void>
  aiSettingsDeleteApiKey(txId: string | undefined | null, id: string): Promise<void>
  aiSettingsClearProviderApiKeyReferences(txId: string | undefined | null, apiKeyId: string, updatedAt: number): Promise<void>
  appConfigIsEmpty(txId?: string | undefined | null): Promise<boolean>
  appConfigIsEmptySync(txId?: string | undefined | null): boolean
  appConfigReadAll(txId?: string | undefined | null): Promise<Array<AppConfigEntryDto>>
  appConfigReadAllSync(txId?: string | undefined | null): Array<AppConfigEntryDto>
  appConfigUpsertMany(txId: string | undefined | null, entries: Array<AppConfigEntryDto>, updatedAt: number): Promise<void>
  appConfigUpsertManySync(txId: string | undefined | null, entries: Array<AppConfigEntryDto>, updatedAt: number): void
  authDataCountUsers(txId?: string | undefined | null): Promise<number>
  authDataCountAdminUsers(txId?: string | undefined | null): Promise<number>
  authDataListUsers(txId?: string | undefined | null): Promise<Array<AuthUserDto>>
  authDataFindUserById(txId: string | undefined | null, id: string): Promise<AuthUserDto | null>
  authDataFindUserByEmail(txId: string | undefined | null, email: string): Promise<AuthUserDto | null>
  authDataInsertUser(txId: string | undefined | null, user: AuthUserDto): Promise<void>
  authDataUpdateUserRole(txId: string | undefined | null, id: string, role: string, updatedAt: number): Promise<void>
  authDataUpdateUserLastLogin(txId: string | undefined | null, id: string, lastLoginAt: number, updatedAt: number): Promise<void>
  authDataDeleteUserById(txId: string | undefined | null, id: string): Promise<void>
  authDataListInvitations(txId?: string | undefined | null): Promise<Array<AuthInvitationDto>>
  authDataFindInvitationById(txId: string | undefined | null, id: string): Promise<AuthInvitationDto | null>
  authDataFindInvitationByToken(txId: string | undefined | null, token: string): Promise<AuthInvitationDto | null>
  authDataInsertInvitation(txId: string | undefined | null, invitation: AuthInvitationDto): Promise<void>
  authDataMarkInvitationUsed(txId: string | undefined | null, id: string, usedByUserId: string, usedAt: number): Promise<void>
  authDataRevokeInvitation(txId: string | undefined | null, id: string, revokedAt: number): Promise<void>
  authDataInsertSession(txId: string | undefined | null, session: AuthSessionDto): Promise<void>
  authDataFindSessionByToken(txId: string | undefined | null, token: string): Promise<AuthSessionDto | null>
  authDataDeleteSessionByToken(txId: string | undefined | null, token: string): Promise<void>
  authDataDeleteSessionsByUserId(txId: string | undefined | null, userId: string): Promise<void>
  authDataDeleteExpiredSessions(txId: string | undefined | null, now: number): Promise<void>
  chatsFindById(txId: string | undefined | null, projectId: string, documentId: string, id: string): Promise<ChatThreadDto | null>
  chatsListByDocument(txId: string | undefined | null, projectId: string, documentId: string): Promise<Array<ChatThreadDto>>
  chatsInsert(txId: string | undefined | null, row: ChatThreadDto): Promise<void>
  chatsUpdate(txId: string | undefined | null, projectId: string, documentId: string, id: string, data: UpdateChatThreadDataDto): Promise<boolean>
  chatsDeleteById(txId: string | undefined | null, projectId: string, documentId: string, id: string): Promise<boolean>
  documentContentFindByDocumentId(txId: string | undefined | null, documentId: string): Promise<DocumentContentDto | null>
  documentContentUpsert(txId: string | undefined | null, documentId: string, contentJson: string, updatedAt: number): Promise<void>
  documentContentDelete(txId: string | undefined | null, documentId: string): Promise<void>
  documentEmbeddingMetadataFindEmbeddings(txId: string | undefined | null, documentId: string, baseUrl: string, model: string): Promise<Array<DocumentEmbeddingDto>>
  documentEmbeddingMetadataGetLatestTimestamp(txId: string | undefined | null, documentId: string, baseUrl: string, model: string): Promise<number | null>
  documentEmbeddingMetadataListVectorReferences(txId: string | undefined | null, documentId: string, baseUrl: string, model: string): Promise<Array<EmbeddingVectorReferenceDto>>
  documentEmbeddingMetadataReplaceEmbeddings(txId: string | undefined | null, input: ReplaceDocumentEmbeddingsInputDto, chunks: Array<ReplaceEmbeddingMetadataChunkDto>): Promise<Array<DocumentEmbeddingDto>>
  documentEmbeddingMetadataDeleteEmbeddingsByDocumentId(txId: string | undefined | null, documentId: string): Promise<void>
  documentEmbeddingMetadataListVectorReferencesByDocumentId(txId: string | undefined | null, documentId: string): Promise<Array<EmbeddingVectorReferenceDto>>
  documentEmbeddingMetadataListVectorReferencesByDocumentIds(txId: string | undefined | null, documentIds: Array<string>): Promise<Array<EmbeddingVectorReferenceDto>>
  documentEmbeddingMetadataDeleteEmbeddingsByVectorKeys(txId: string | undefined | null, vectorKeys: Array<string>): Promise<number>
  documentEmbeddingMetadataGetVectorPayloadContext(txId: string | undefined | null, documentId: string): Promise<DocumentVectorPayloadContextDto>
  documentEmbeddingMetadataListSearchMetadataByVectorKeys(txId: string | undefined | null, vectorKeys: Array<string>): Promise<Record<string, EmbeddingSearchMetadataDto>>
  documentEmbeddingsFindEmbeddings(txId: string | undefined | null, documentId: string, baseUrl: string, model: string): Promise<Array<DocumentEmbeddingDto>>
  documentEmbeddingsSearch(txId: string | undefined | null, input: SearchDocumentEmbeddingsInputDto): Promise<Array<EmbeddingSearchMatchDto>>
  documentEmbeddingsReplaceEmbeddings(txId: string | undefined | null, input: ReplaceDocumentEmbeddingsInputDto): Promise<ReplaceDocumentEmbeddingsResultDto>
  documentEmbeddingsListVectorReferencesByDocumentIds(txId: string | undefined | null, documentIds: Array<string>): Promise<Array<EmbeddingVectorReferenceDto>>
  documentEmbeddingsDeleteVectorsByReferences(txId: string | undefined | null, references: Array<EmbeddingVectorReferenceDto>): Promise<void>
  documentEmbeddingsDeleteEmbeddingsByDocumentId(txId: string | undefined | null, documentId: string): Promise<void>
  documentNotesListByDocumentId(txId: string | undefined | null, documentId: string): Promise<Array<DocumentNoteDto>>
  documentNotesReplaceAllForDocument(txId: string | undefined | null, documentId: string, notes: Array<DocumentNoteDto>): Promise<void>
  documentNotesDeleteByDocumentId(txId: string | undefined | null, documentId: string): Promise<void>
  documentsFindById(txId: string | undefined | null, id: string): Promise<DocumentDto | null>
  documentsFindByIds(txId: string | undefined | null, ids: Array<string>): Promise<Array<DocumentDto>>
  documentsInsert(txId: string | undefined | null, document: DocumentDto): Promise<void>
  documentsUpdate(txId: string | undefined | null, id: string, data: UpdateDocumentDataDto): Promise<void>
  documentsDeleteById(txId: string | undefined | null, id: string): Promise<void>
  indexingSettingsGet(txId: string | undefined | null, scopeType: string, scopeId: string): Promise<IndexingSettingsDto | null>
  indexingSettingsGetMany(txId: string | undefined | null, scopeType: string, scopeIds: Array<string>): Promise<Array<IndexingSettingsDto>>
  indexingSettingsUpsert(txId: string | undefined | null, input: UpsertIndexingSettingsDto): Promise<IndexingSettingsDto>
  indexingSettingsDelete(txId: string | undefined | null, scopeType: string, scopeId: string): Promise<void>
  jobQueueEnqueue(txId: string | undefined | null, input: EnqueueJobInputDto): Promise<QueueJobDto>
  jobQueueUpsertUnique(txId: string | undefined | null, input: UpsertUniqueJobInputDto): Promise<QueueJobDto>
  jobQueueLease(txId: string | undefined | null, input: LeaseJobsInputDto): Promise<Array<QueueJobDto>>
  jobQueueComplete(txId: string | undefined | null, input: CompleteLeasedJobInputDto): Promise<string>
  jobQueueFail(txId: string | undefined | null, input: FailLeasedJobInputDto): Promise<string>
  jobQueueGetByTypeAndDedupeKey(txId: string | undefined | null, jobType: string, dedupeKey: string): Promise<QueueJobDto | null>
  jobQueueGetByTypeAndDedupeKeys(txId: string | undefined | null, jobType: string, dedupeKeys: Array<string>): Promise<Array<QueueJobDto>>
  jobQueueListQueuedByType(txId: string | undefined | null, jobType: string): Promise<Array<QueueJobDto>>
  jobQueueDeleteQueuedByTypeAndDedupeKeys(txId: string | undefined | null, jobType: string, dedupeKeys: Array<string>): Promise<void>
  jobQueueGetTypeStats(txId: string | undefined | null, jobType: string): Promise<JobQueueTypeStatsDto>
  projectDocumentsInsert(txId: string | undefined | null, row: ProjectDocumentDto): Promise<void>
  projectDocumentsHasProjectDocument(txId: string | undefined | null, projectId: string, documentId: string): Promise<boolean>
  projectDocumentsFindAssociatedDocumentIds(txId: string | undefined | null, projectId: string, documentIds: Array<string>): Promise<Array<string>>
  projectDocumentsListDocumentIds(txId?: string | undefined | null): Promise<Array<string>>
  projectDocumentsFindSoleDocumentIdsByProjectId(txId: string | undefined | null, projectId: string): Promise<Array<string>>
  projectDocumentsFindProjectIdsByDocumentId(txId: string | undefined | null, documentId: string): Promise<Array<string>>
  projectDocumentsFindSoleProjectIdByDocumentId(txId: string | undefined | null, documentId: string): Promise<string | null>
  projectDocumentsFindSoleProjectIdsByDocumentIds(txId: string | undefined | null, documentIds: Array<string>): Promise<Record<string, string>>
  projectsFindAll(txId?: string | undefined | null): Promise<Array<ProjectDto>>
  projectsFindByOwnerUserId(txId: string | undefined | null, ownerUserId: string): Promise<Array<ProjectDto>>
  projectsFindById(txId: string | undefined | null, id: string): Promise<ProjectDto | null>
  projectsFindByIds(txId: string | undefined | null, ids: Array<string>): Promise<Array<ProjectDto>>
  projectsInsert(txId: string | undefined | null, project: ProjectDto): Promise<void>
  projectsUpdate(txId: string | undefined | null, id: string, data: UpdateProjectDataDto): Promise<void>
  projectsDeleteById(txId: string | undefined | null, id: string): Promise<void>
  versionSnapshotsFindById(txId: string | undefined | null, id: string): Promise<VersionSnapshotDto | null>
  versionSnapshotsFindMetadataByDocumentId(txId: string | undefined | null, documentId: string): Promise<Array<VersionSnapshotMetaDto>>
  versionSnapshotsFindCursorById(txId: string | undefined | null, documentId: string, id: string): Promise<VersionSnapshotCursorDto | null>
  versionSnapshotsInsert(txId: string | undefined | null, snapshot: VersionSnapshotDto): Promise<void>
  versionSnapshotsDeleteSnapshotsAfterCursor(txId: string | undefined | null, documentId: string, cursorCreatedAt: number, cursorRowId: number): Promise<void>
  persistBundle(txId: string | undefined | null, input: PersistBundleInputDto): Promise<void>
  yjsGetPersisted(txId: string | undefined | null, documentId: string): Promise<Buffer | null>
  yjsSet(txId: string | undefined | null, documentId: string, data: Buffer): Promise<void>
  yjsDelete(txId: string | undefined | null, documentId: string): Promise<void>
  jobQueueWaitForAvailable(txId: string | undefined | null, now: number, timeoutMs: number, typesJson?: string | undefined | null): Promise<WaitForAvailableResult>
  importMarkdownDocuments(request: MassImportRequest): Promise<string>
}

export declare class NativeTransactionHandle {
  id(): string
  commit(): Promise<void>
  rollback(): Promise<void>
}

export interface AiApiKeyDto {
  id: string
  baseUrl: string
  name: string
  apiKey: string
  isDefault: boolean
  createdAt: number
  updatedAt: number
}

export interface AiModelSelectionDto {
  usage: string
  scopeType: string
  scopeId: string
  providerConfigId: string
  updatedAt: number
}

export interface AiProviderConfigDto {
  id: string
  usage: string
  name?: string
  providerId: string
  type: string
  baseUrl: string
  model: string
  apiKeyId?: string
  customHeadersJson: string
  sortOrder: number
  createdAt: number
  updatedAt: number
}

export interface AppConfigEntryDto {
  key: string
  value: string
}

export interface AuthInvitationDto {
  id: string
  token: string
  email?: string
  role: string
  createdByUserId: string
  createdAt: number
  expiresAt: number
  revokedAt?: number
  usedAt?: number
  usedByUserId?: string
}

export interface AuthSessionDto {
  token: string
  userId: string
  createdAt: number
  expiresAt: number
}

export interface AuthUserDto {
  id: string
  name: string
  email: string
  passwordHash: string
  role: string
  createdAt: number
  updatedAt: number
  lastLoginAt?: number
}

export interface ChatThreadDto {
  id: string
  projectId: string
  documentId: string
  title: string
  messages: string
  createdAt: number
  updatedAt: number
}

export interface CompleteLeasedJobInputDto {
  id: string
  workerId: string
  expectedUpdatedAt?: number
}

export interface DocumentContentDto {
  documentId: string
  content: string
  updatedAt: number
}

export interface DocumentDto {
  id: string
  title: string
  type: string
  metadataJson?: string
  createdAt: number
  updatedAt: number
}

export interface DocumentEmbeddingDto {
  id: number
  vectorKey: string
  documentId: string
  providerConfigId?: string
  providerId: string
  type: string
  baseUrl: string
  model: string
  strategyType: string
  strategyPropertiesJson: string
  chunkOrdinal: number
  chunkStart: number
  chunkEnd: number
  selectionFrom?: number
  selectionTo?: number
  chunkText: string
  dimensions: number
  documentTimestamp: number
  contentHash: string
  createdAt: number
  updatedAt: number
}

export interface DocumentNoteDto {
  id: string
  documentId: string
  anchorKind: string
  anchorId: string
  content: string
  authorUserId: string
  createdAt: number
  updatedAt: number
}

export interface DocumentVectorPayloadContextDto {
  documentId: string
  title: string
  projectIdsJson: string
  parentDirectory: string
  directoryAncestorsJson: string
}

/** A single document preparation request for embedding generation. */
export interface EmbeddingDocumentRequest {
  documentId: string
  title: string
  content: string
  strategyJson: string
}

export interface EmbeddingSearchMatchDto {
  documentId: string
  title: string
  createdAt: number
  updatedAt: number
  strategyType: string
  chunkOrdinal: number
  chunkStart: number
  chunkEnd: number
  selectionFrom?: number
  selectionTo?: number
  chunkText: string
  distance: number
}

export interface EmbeddingSearchMetadataDto {
  vectorKey: string
  documentId: string
  title: string
  createdAt: number
  updatedAt: number
  strategyType: string
  chunkOrdinal: number
  chunkStart: number
  chunkEnd: number
  selectionFrom?: number
  selectionTo?: number
  chunkText: string
}

export interface EmbeddingVectorReferenceDto {
  documentId: string
  vectorKey: string
  baseUrl: string
  model: string
  dimensions: number
  vectorRowId?: number
}

export interface EnqueueJobInputDto {
  type: string
  dedupeKey?: string
  payloadJson: string
  runAt?: number
  maxAttempts?: number
  priority?: number
}

export interface FailLeasedJobInputDto {
  id: string
  workerId: string
  now: number
  error: string
  retryDelayMs: number
}

export interface IndexingSettingsDto {
  scopeType: string
  scopeId: string
  strategyType: string
  strategyPropertiesJson: string
  updatedAt: number
}

export interface JobQueueTypeStatsDto {
  totalQueued: number
  nextAvailableAt?: number
  oldestQueuedAt?: number
}

export interface LeaseJobsInputDto {
  workerId: string
  now: number
  leaseDurationMs: number
  limit: number
  typesJson?: string
}

export interface MarkdownHtmlDetection {
  htmlTagCount: number
  tags: Record<string, number>
  hasLikelyHtmlBlocks: boolean
}

export interface MarkdownImportPlanOptions {
  maxDocChars: number
  targetDocChars?: number
  split: MarkdownSplitStrategy
  rawHtmlMode?: MarkdownRawHtmlMode
}

export interface MarkdownImportPlanPart {
  markdown: string
  suggestedTitle?: string
  estimatedChars: number
}

export interface MarkdownImportPlanResult {
  normalizedMarkdown: string
  parts: Array<MarkdownImportPlanPart>
  html: MarkdownHtmlDetection
}

export interface MarkdownParseOptions {
  rawHtmlMode?: MarkdownRawHtmlMode
}

export declare const enum MarkdownRawHtmlMode {
  Drop = 'Drop',
  CodeBlock = 'CodeBlock'
}

export interface MarkdownSplitStrategy {
  type: string
  level?: number
}

export interface MassImportDocumentInput {
  title: string
  markdown: string
}

export interface MassImportRequest {
  projectId: string
  documents: Array<MassImportDocumentInput>
  parseFailureMode?: string
  rawHtmlMode?: MarkdownRawHtmlMode
}

export declare function parseMarkdown(input: string, options: MarkdownParseOptions): string

export interface PersistBundleInputDto {
  documentId: string
  yjsData: Buffer
  contentJson: string
  contentUpdatedAt: number
  notesJson: string
  snapshotId?: string
  snapshotContentJson?: string
  snapshotCreatedAt?: number
}

export declare function planMarkdownImport(markdown: string, options: MarkdownImportPlanOptions): MarkdownImportPlanResult

/** A prepared chunk that is ready to be sent to an embedding model. */
export interface PreparedEmbeddingChunk {
  ordinal: number
  start: number
  end: number
  selectionFrom?: number
  selectionTo?: number
  estimatedTokens: number
  text: string
}

/** A prepared document output with the projection text plus chunk metadata. */
export interface PreparedEmbeddingDocument {
  documentId: string
  projectionText: string
  chunks: Array<PreparedEmbeddingChunk>
}

export declare function prepareEmbeddingDocuments(requests: Array<EmbeddingDocumentRequest>): Promise<Array<PreparedEmbeddingDocument>>

export interface ProjectDocumentDto {
  projectId: string
  documentId: string
  addedAt: number
}

export interface ProjectDto {
  id: string
  title: string
  ownerUserId: string
  metadataJson?: string
  createdAt: number
  updatedAt: number
}

export interface QueueJobDto {
  id: string
  type: string
  dedupeKey?: string
  payloadJson: string
  availableAt: number
  leaseOwner?: string
  leaseUntil?: number
  attempt: number
  maxAttempts: number
  priority: number
  createdAt: number
  updatedAt: number
  lastError?: string
}

export interface ReplaceDocumentEmbeddingsInputDto {
  documentId: string
  providerConfigId?: string
  providerId: string
  type: string
  baseUrl: string
  model: string
  strategyType: string
  strategyPropertiesJson: string
  documentTimestamp: number
  contentHash: string
  chunks: Array<ReplaceEmbeddingChunkDto>
  createdAt: number
  updatedAt: number
}

export interface ReplaceDocumentEmbeddingsResultDto {
  status: string
  embeddings: Array<DocumentEmbeddingDto>
}

export interface ReplaceEmbeddingChunkDto {
  ordinal: number
  start: number
  end: number
  selectionFrom?: number
  selectionTo?: number
  text: string
  vectorKey?: string
  embeddingJson: string
}

export interface ReplaceEmbeddingMetadataChunkDto {
  vectorKey: string
  ordinal: number
  start: number
  end: number
  selectionFrom?: number
  selectionTo?: number
  text: string
  dimensions: number
}

export interface SearchDocumentEmbeddingsInputDto {
  projectId?: string
  documentId?: string
  baseUrl: string
  model: string
  queryEmbeddingJson: string
  limit: number
  scopeType: string
  directoryPath?: string
}

export interface UpdateAiApiKeyDataDto {
  name?: string
  apiKey?: string
  updatedAt: number
}

export interface UpdateChatThreadDataDto {
  title?: string
  messages?: string
  updatedAt: number
}

export interface UpdateDocumentDataDto {
  title?: string
  metadataJson?: string
  clearMetadata: boolean
  updatedAt: number
}

export interface UpdateProjectDataDto {
  title?: string
  ownerUserId?: string
  metadataJson?: string
  clearMetadata: boolean
  updatedAt: number
}

export interface UpsertAiModelSelectionDto {
  usage: string
  scopeType: string
  scopeId: string
  providerConfigId: string
  updatedAt: number
}

export interface UpsertAiProviderConfigDto {
  id: string
  usage: string
  name?: string
  providerId: string
  type: string
  baseUrl: string
  model: string
  apiKeyId?: string
  customHeadersJson: string
  sortOrder: number
  createdAt: number
  updatedAt: number
}

export interface UpsertIndexingSettingsDto {
  scopeType: string
  scopeId: string
  strategyType: string
  strategyPropertiesJson: string
  updatedAt: number
}

export interface UpsertUniqueJobInputDto {
  type: string
  dedupeKey: string
  payloadJson: string
  runAt: number
  maxAttempts?: number
  priority?: number
}

export interface VersionSnapshotCursorDto {
  id: string
  documentId: string
  content: string
  createdAt: number
  rowId: number
}

export interface VersionSnapshotDto {
  id: string
  documentId: string
  content: string
  createdAt: number
}

export interface VersionSnapshotMetaDto {
  id: string
  documentId: string
  createdAt: number
}

export interface WaitForAvailableResult {
  reason: string
}
